version: "3.8"
services:
  target:
    container_name: target
    image: tleemcjr/metasploitable2
    tty: true
    ports:
      - "3001:80"
    networks:
      - pentest
    volumes:
      - ./scripts/target:/home/scripts
  attacker:
    container_name: attacker
    image: kalilinux/kali-rolling
    tty: true
    networks:
      - pentest
    volumes:
      - ./scripts/attacker:/home/scripts
networks:
  pentest: